spring:
  application:
    name: agora-system-market

  datasource:
    url: [ YOUR-DATABASE-URL ]
    username: [ YOUR-USERNAME ]
    password: [ YOUR-PASSWORD ]
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    default-schema: market
    create-schemas: true